; PlatformIO Project Configuration File
;
; Build options: build flags, source and extra script
; Upload options: custom upload port, speed and extra flags
; Library options: dependencies, extra library storages
; Advanced options: extra scripting
;
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = heltec_wifi_lora_32_V3
description = LoRa Antenna Phaser - Remote relay control and telemetry (Heltec V3)

[env:heltec_wifi_lora_32_V3]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
; Build options
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
; Upload options
upload_protocol = esptool
upload_speed = 921600
board_upload.after_reset = hard_reset
; Monitor options
monitor_speed = 115200
monitor_filters = time, log2file
monitor_dtr = 0
monitor_rts = 0
monitor_port = hwgrep://303A:1001
upload_port  = hwgrep://303A:1001
; Libraries
lib_deps =
    jgromes/RadioLib@^7.0.0
    adafruit/Adafruit INA219@^1.2.3
; Build flags for Heltec V3 (ESP32-S3, USB CDC)
build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D HELTEC_V3
    -D ANTENNA_CONFIG=1 ;1 RemoteQTH 2 Comtek
